[libGDX] 1.9.10 -> 1.11.0
mapsforge/vtm pull request #972
Opened 2022-11-13 18:07 UTC by wolfgang-ch

This PR contains modifications to run VTM with libGDX 1.11.0

I've tested `org.oscim.test.MapsforgeTest` with Windows 10 sucessfully, it also worked in my project MyTourbook with Windows and Linux

This was the `settings.gradle` which I used to build it, I disabled all includes which I cannot test/build. I use this modified setup also in my project.

I think, that porting to the other platforms should not be much work

![image](https://user-images.githubusercontent.com/1283445/201536645-5140113e-a870-4b55-baad-432d1edbff56.png)

2022-11-13 18:13 UTC, devemux86 commented on build.gradle
> +                options.compilerArgs.addAll(['--release', '8'])
Why is this needed?

2022-11-13 18:15 UTC, devemux86 commented
Thanks, however the build [fails](https://github.com/mapsforge/vtm/actions/runs/3456358769).

That's why I mentioned that advancing libGDX requires several changes.
Pull requests must build successfully all modules.

2022-11-13 18:17 UTC, devemux86 commented on build.gradle
> +        targetCompatibility = JavaVersion.VERSION_1_8
Why is this needed?

2022-11-13 18:24 UTC, devemux86 requested changes
Thanks, however the build [fails](https://github.com/mapsforge/vtm/actions/runs/3456358769).

That's why mentioned that updating libGDX requires VTM changes.
_Pull requests must build successfully all modules._

Android is an important platform of VTM, can test it on Android emulator.

2022-11-14 05:39 UTC, wolfgang-ch commented
Something went wrong with your comment, it's not available any more

![image](https://user-images.githubusercontent.com/1283445/201583580-0a16cc2f-5e44-4dd7-b118-d7c4f962b46c.png)

My Answer:

This error occurred with Java 7

![image](https://user-images.githubusercontent.com/1283445/201583765-607cac5c-2a8b-425b-a78f-d5cd6e19152a.png)

2022-11-14 05:46 UTC, wolfgang-ch commented
> _Pull requests must build successfully all modules._

I cannot fulfill these requirements, I've zero Android experience and no iOS/OSX to test it, I close this PR and maybe someone else can cherry pick this commit

2022-11-14 05:46 UTC, closed without merging

2022-11-14 09:25 UTC, devemux86 commented
> This error occurred with Java 7

Then the required module could be updated, but not the whole library.

> I've zero Android experience and no iOS/OSX to test it, I close this PR and maybe someone else can cherry pick this commit

I don't have a Mac either, but the modules have to be built or the library can't be published.

I may check for a newer libGDX version when I have free time.

2022-11-15 11:54 UTC, devemux86 commented
Thanks, merged via 36e4116d39ec2f2e27b13241d7babd4c69491d25 and fixed the other platforms via e1191f68ae3f8f591d0205e216d0f39f43e2fea5.

(for iOS see https://github.com/MobiVM/robovm/pull/394#issuecomment-516028463)

2022-11-15 14:13 UTC, wolfgang-ch commented
> > This error occurred with Java 7
> 
> Then the required module could be updated, but not all platforms.

My gradle skills are not so good to apply the best changes but I've seen that you have done it in your commit 👍